@startuml 
start
:Вход: Отфильтрованный список фронтиров;
:Очистить список центроидов;
if (Список фронтиров не пуст?) then (да)
  :Конвертировать фронтиры в PCL PointCloud;
  :Построить KD-Tree;
  :Выполнить Euclidean Cluster Extraction\n(tolerance, min/max size);
  :Получить индексы кластеров;
  while (Обработка кластеров)
   :Взять следующий кластер (индексы);
   :Вычислить центроид кластера;
   :Получить размер кластера;
   :Добавить (центроид, размер) в список;
  endwhile
endif
:Выход: Список пар (центроид, размер);
stop

@enduml