@startuml 
start
:Вход: OctoMap, Список сырых фронтиров;
:Создать новый отфильтрованный список;
while (Обработка точек из списка)
  :Взять точку фронтира;
  :Проверить близость к занятым вокселям\nв радиусе min_obstacle_distance_\n(isCloseToObstacle);
  if (Не близко к препятствию?) then (да)
    :Добавить точку в отфильтрованный список;
  endif
endwhile
:Выход: Отфильтрованный список фронтиров;
stop

@enduml