@startuml 
start
:Вход: OctoMap, Поза дрона;
:Очистить список фронтиров;
:Определить область поиска (BBox) вокруг дрона;
repeat
  :Взять следующий воксель в BBox;
  if (Воксель в допуске по высоте?) then (да)
    if (Воксель свободен?) then (да)
      :Проверить 6 соседей;
      :Подсчитать неизвестных (U) и свободных (F) соседей;
      if (U >= 1 AND F >= min_free_neighbors_?) then (да)
        :Добавить центр вокселя в список фронтиров;
      endif
    endif
  endif
repeat while (Есть еще воксели в BBox?)
:Выход: Список сырых фронтиров;
stop

@enduml