@startuml
start
:Открыть файл;
if (Не удалось открыть?) then (да)
  stop
endif
:Читать заголовок;
while (Строка != "end_header")
  :Обработать строку заголовка\n(формат, элемент vertex, свойства x,y,z);
endwhile
if (Заголовок некорректен?) then (да)
  :Закрыть файл;
  stop
endif
if (Число точек (N) == 0) then (да)
  :Закрыть файл;
  :Вернуть успех (пустое облако);
  stop
endif
:Резервировать память для N точек;
:Читать данные точек;
repeat
  :Прочитать строку данных (x y z);
  if (Ошибка чтения?) then (да)
     :Закрыть файл;
     stop
  endif
  :Добавить точку в облако;
repeat while (Прочитано < N точек)
:Закрыть файл;
:Вернуть успех;
stop

@enduml