@startuml 

start
:Создать сообщение;
:Заполнить заголовок (время, frame_id);
:Получить оценку состояния из EKF (ориентация, смещение гиро);
:Заполнить ориентацию и ковариацию;
:Вычислить скорректированную угловую скорость;
:Заполнить угловую скорость и ковариацию;
:Заполнить линейное ускорение (измеренное) и ковариацию;
:Вернуть сообщение;
stop

@enduml