@startuml
start
if (Соединение активно?) then (да)
  :Отправить запрос IMU;
  if (Запрос отправлен?) then (да)
    :Прочитать ответ IMU;
    if (Ответ получен?) then (да)
      :Подготовить данные для EKF;
      :Выполнить EKF predict;
      :Заполнить и опубликовать ROS IMU сообщение;
    else (нет)
      :Ошибка чтения;
    endif
  else (нет)
    :Ошибка отправки;
  endif
else (нет)
  :Попытка переподключения;
  if (Переподключение не удалось?) then (да)
     stop
  endif
endif
stop

@enduml