@startuml 
start
if (Невалидные входные параметры или облако пустое?) then (да)
  :Вернуть исходное/пустое облако;
  stop
endif
:Вычислить Bounding Box облака;
if (Bounding Box невалиден?) then (да)
  :Вернуть исходное облако;
  stop
endif
:**Построить Voxel Grid**;
:Создать пустое отфильтрованное облако;
while (Для каждой точки i во входном облаке)
  :**Подсчитать кол-во соседей N в радиусе**;
  if (N >= min_neighbors?) then (да)
    :Добавить точку i в отфильтрованное облако;
  endif
endwhile
:Вернуть отфильтрованное облако;
stop

@enduml