@startuml
start
:Получить запрос (req.name);
:Проверить pSLAM != nullptr;
:Вызвать pSLAM->SaveMap(req.name) (сохранение .osa);
:Прочитать параметры (путь, фильтр вкл/выкл, тип фильтра, параметры фильтра);
:Создать директорию для сохранения;
:Вызвать pSLAM->GetAllMapPointsAsPCL();
if (Облако точек получено?) then (да)
  :Сохранить "сырое" облако в _raw.pcd;
  if (Фильтрация включена?) then (да)
   :Выбрать и применить фильтр (SOR/ROR);
   if (Отфильтрованное облако не пустое?) then (да)
     :Сохранить отфильтрованное облако в _filtered.pcd;
     :filtered_saved = true;
   else (нет)
     :filtered_saved = false;
   endif
  else (нет)
  endif
  :res.success = raw_saved && (!enable_filter || filtered_saved);
else (нет)
  :res.success = false;
endif
:Отправить ответ;
stop

@enduml