@startuml
start
if (Подключен?) then (Да)
    :Установка таймаута;
    while (Есть данные для отправки?) is (Да)
        :Отправка части данных (send);
        if (Ошибка отправки?) then (Да)
            :Обработка ошибки (лог, разрыв);
            :Возврат -1;
            stop
        endif
    endwhile (Нет)
    :Возврат кол-ва байт;
else (Нет)
    :Возврат -1 (Не подключен);
endif
stop

@enduml