@startuml

start
:Инициализация\n(Подключение, Клавиатура, Арминг Дрона);

repeat :Цикл Управления:
  :Чтение Клавиатуры;
  if (Нажата Клавиша Управления?) then (да)
    :Обновить RC\n(Задать целевые значения);
  else (нет)
    :Обновить RC\n(Вернуть оси к центру);
  endif
  :Отправить RC Команды\n(MSP_SET_RAW_RC);
  :Пауза (Rate);
repeat while (Продолжать?) is (да)
-> нет;

:Завершение\n(Восстановить Клавиатуру, Disarm);
stop

@enduml